spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/Dev/LearningMicroservicesWithSpringBoot02/social-multiplication-db;DB_CLOSE_ON_EXIT=FALSE;